### ISSUE TITLE
Recursive objects

### ISSUE THREAD

**Issue by praveenjayaraman** [mohsen1/json-schema-view#12]
How does the handle objects having recursion or objects with multiple attributes of same type.

Ex -
Recursion
Person {"name":"string", "age":"string", "friends" : ["$ref:Person"]}

Attributes of same type
Amount {"CurrencyEnum":"USD, GBP,....", "value":"double"}
Item {"title":"string", "cost" : "$ref:Amount", "shipping" : "$ref:Amount", "tax" : "$ref:Amount", "discount" : "$ref:Amount"}

Do we need to expand each attribute for the directive to work ?

Thanks in advance

**Comment by mohsen1** [comment]
This directive does not resolve JSON References. I don't think it should either. For resolving JSON References you can use [json-refs](https://github.com/whitlockjc/json-refs). For recursive references json-refs offers an option to resolve it down to a certain level. So in your Person example, if you resolve down to 3 levels, you would have 

```
Person->Friends->Person->Friends->Person->Friends->null
```

**Comment by praveenjayaraman** [comment]
Is there any support for enums ? 

In the above case, how should CurrencyEnum be represented ?

Thanks

**Comment by mohsen1** [comment]
Follow #11 for enums

**Comment by mohsen1** [comment]
Enums are now working.
