### ISSUE TITLE
Support $ref within schemas

### ISSUE THREAD

**Issue by ghost** [mohsen1/json-schema-view#16]
I'm guessing its not currently supported as I get an 'Undefined' in the output

**Comment by mohsen1** [comment]
Do you mean it should resolve the `$ref` references or just render them?

For resolving $refs take a look at [this](http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html)

**Comment by ghost** [comment]
Sorry yes, resolving them would have been ideal, but I just spotted an earlier ticket where you said you didn't feel this should be in the product. 
I have instead, used json-refs js, to run within my swagger gen, which works just perfectly! I'll close this off, thanks for quick reply!
