### ISSUE TITLE
Required doesn't render any differently

### ISSUE THREAD

**Issue by fishermand46** [mohsen1/json-schema-view#5]
It doesn't look like required attributes are rendered any differently than optional ones. Even in the [example](http://azimi.me/json-schema-view/demo/demo.html) I can see a difference.

**Comment by mohsen1** [comment]
It should render a red \* next to it.

**Comment by fishermand46** [comment]
Tracked it down to this commit e3aa6ba. That's when the `json-schema-view simple schema should put an asterisk next to required properties` test failed.

**Comment by fishermand46** [comment]
Looks like you got rid of the addPropertyName function, which gave a name to every property object, but then when you call `schema.name` [here](https://github.com/mohsen1/json-schema-view/blob/e3aa6ba607663e21591a0510cc9557cdb17a25d0/dist/json-schema-view.js#L40), it hasn't been set.
